# Generated by Django 5.2.15 on 2026-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dscription', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Volunteers', models.ManyToManyField(blank=True, to='volunteers.volunteer')),
            ],
        ),
    ]
