# Generated by Django 5.2.15 on 2026-07-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Volunteers',
            new_name='volunteers',
        ),
    ]
