# Generated by Django 5.2.15 on 2026-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('total_donated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
