# Generated by Django 5.2.15 on 2026-07-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_alter_drivevolunteer_status'),
        ('events', '0001_initial'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='experience',
            field=models.TextField(blank=True, help_text='Previous volunteer experience'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text='List of interests'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='motivation',
            field=models.TextField(blank=True, help_text='Why do you want to volunteer?'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='Gamification points'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='VolunteerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/')),
                ('drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='drives.drive')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='events.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
