# Generated by Django 5.2.15 on 2026-07-23 07:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('profile_picture', models.FileField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profiles/%Y/%m/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('full_address', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('donor', 'Donor'), ('volunteer', 'Volunteer'), ('manager', 'Drive Manager'), ('admin', 'Admin')], default='donor', max_length=20)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wants_to_donate', models.BooleanField(default=False)),
                ('wants_to_volunteer', models.BooleanField(default=False)),
                ('wants_to_manage', models.BooleanField(default=False)),
                ('preferred_role', models.CharField(blank=True, max_length=50)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], default='beginner', max_length=20)),
                ('preferred_categories', models.JSONField(blank=True, default=list, help_text='List of preferred drive categories')),
                ('skills', models.TextField(blank=True, help_text='Your skills and expertise')),
                ('availability_hours', models.PositiveIntegerField(default=0, help_text='Hours per week you can contribute')),
                ('availability_days', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('both', 'Both'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('motivation', models.TextField(blank=True, help_text='What motivates you to join HopeBridge?')),
                ('future_goals', models.TextField(blank=True, help_text='Your goals with HopeBridge')),
                ('how_did_you_hear', models.CharField(blank=True, max_length=100)),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
