# Generated by Django 5.2.15 on 2026-07-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donations',
            new_name='Donation',
        ),
    ]
