# Generated by Django 5.2.15 on 2026-07-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivevolunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='active', max_length=20),
        ),
    ]
