# Generated by Django 5.2.15 on 2026-07-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('relief', 'Relief Program'), ('education', 'Education Sponsorship'), ('food_drive', 'Food Drive'), ('book_donation', 'Book Donation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donors.donor')),
            ],
        ),
    ]
