# Generated by Django 5.2.15 on 2026-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HopeBridge NGO', max_length=200)),
                ('contact_email', models.EmailField(default='contact@hopebridge.org', max_length=254)),
                ('contact_phone', models.CharField(default='+1 234 567 8900', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, help_text='e.g. 80G/12A Registration Number', max_length=50)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.FileField(blank=True, null=True, upload_to='org_settings/')),
            ],
            options={
                'verbose_name': 'Organization Settings',
                'verbose_name_plural': 'Organization Settings',
            },
        ),
    ]
