# Generated by Django 5.2.15 on 2026-07-23 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('donation', 'Donation'), ('drive', 'Drive'), ('event', 'Event'), ('system', 'System'), ('assignment', 'Assignment')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, help_text='URL to open on click')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
