# Generated by Django 5.2.15 on 2026-07-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('donation', 'Donation'), ('volunteer', 'Volunteer'), ('admin', 'Admin'), ('security', 'Security'), ('general', 'General'), ('announcement', 'Announcements')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('donation_success', 'Donation Successful'), ('allocation_updated', 'Allocation Updated'), ('volunteer_approved', 'Volunteer Approved'), ('volunteer_assigned', 'Volunteer Assigned'), ('drive_completed', 'Drive Completed'), ('announcement', 'Announcement'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('system_alert', 'System Alert')], default='system_alert', max_length=30),
        ),
    ]
